# Generated by Django 4.2.7 on 2024-01-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lobby_vs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='vs',
        ),
    ]
