# Generated by Django 4.2.7 on 2024-01-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lobby_vs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lobby',
        ),
    ]
