# Generated by Django 4.2.7 on 2024-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_delete_lobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('grid11', models.IntegerField(default=0)),
                ('grid12', models.IntegerField(default=0)),
                ('grid13', models.IntegerField(default=0)),
                ('grid21', models.IntegerField(default=0)),
                ('grid22', models.IntegerField(default=0)),
                ('grid23', models.IntegerField(default=0)),
                ('grid31', models.IntegerField(default=0)),
                ('grid32', models.IntegerField(default=0)),
                ('grid33', models.IntegerField(default=0)),
            ],
        ),
    ]
