# Generated by Django 4.2.7 on 2024-01-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='grid11',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid12',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid13',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid21',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid22',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid23',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid31',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid32',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='grid33',
        ),
    ]
