# Generated by Django 4.2.7 on 2024-01-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_lobby_grid11_remove_lobby_grid12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='master',
            new_name='guest',
        ),
    ]
